### ISSUE TITLE
[README] php artisan migrate step is missing

### ISSUE THREAD

**Issue by sebastianbachmann** [drehimself/lc-voting#5]
Hi,

can you please add an additional step to migrate the database before running _php artisan serve_?
I cloned the repo and followed the instructions in the README and was running into an error. _php artisan migrate_ fixed it, so i guess this step is missing.

Thanks for doing this project, i am totally new to Laravel and i am learning a lot!

P.S. i hope opening an issue instead sending a Pull Request is ok, since it's just a small change.

**Comment by drehimself** [comment]
Added. Dunno how I missed that step 😅

**Comment by sebastianbachmann** [comment]
Thanks 😅
